### ISSUE TITLE
Wanted to add solution of 'Searching an element in a sorted array' problem

### ISSUE THREAD

**Issue by Chinmayee7697** [random957654/Hactober-2023-1#134]
Please do assign me for this.

**Comment by Parvsharma04** [comment]
please add the hactober-accepted label to this issue

**Comment by MSubhajitIND** [comment]
> please add the hactober-accepted label to this issue

Labels only need in Pull request although i add it ..please read #86 thread

**Comment by Ishika0-0** [comment]
@random957654 Can I also contribute to #134 issue

**Comment by MSubhajitIND** [comment]
> @random957654 Can I also contribute to #134 issue

Ya you can

**Comment by mehakbasrani** [comment]
Please Assign it to me

**Comment by MSubhajitIND** [comment]
> Please Assign it to me

Assigned

**Comment by truptiQL** [comment]
Please assign it to me. I want to contribute

**Comment by Soumojitshome2023** [comment]
Binary Searching

 `#include <stdio.h>

int linearSearch(int arr[], int size, int element)
{
    /*
    Best Time Complexity : O(1)
    Average Time Complexity : O(n)
    Worst Time Complexity : O(n)
    Worst Space Complexity : O(1)
    */
    for (int i = 0; i < size; i++)
    {
        if (arr[i] == element)
        {
            return i;
        }
    }
    return -1;
}

int binarySearch(int arr[], int size, int element)
{
    /*
    Best Time Complexity : O(1)
    Average Time Complexity : O(logn)
    Worst Time Complexity : O(logn)
    Worst Space Complexity : O(1)
    */

    int low, mid, high;
    low = 0;
    high = size - 1;
    // Keep searching until low <= high
    while (low <= high)
    {
        mid = (low + high) / 2;
        if (arr[mid] == element)
        {
            return mid;
        }
        if (arr[mid] < element)
        {
            low = mid + 1;
        }
        else
        {
            high = mid - 1;
        }
    }
    return -1;
}

int main()
{
    // Unsorted array for linear search
    // int arr[] = {1,3,5,56,4,3,23,5,4,54634,56,34};
    // int size = sizeof(arr)/sizeof(int);

    // Sorted array for binary search
    int arr[] = {1, 3, 5, 56, 64, 73, 123, 225, 444};
    int size = sizeof(arr) / sizeof(int);
    int element = 444;
    int searchIndex = binarySearch(arr, size, element);
    printf("The element %d was found at index %d \n", element, searchIndex);
    return 0;
}
`
