### ISSUE TITLE
Dutch National flag algorithm Sort an array of 0s, 1s and 2s.

### ISSUE THREAD

**Issue by shanvijha30** [random957654/Hactober-2023-1#200]
Given an array consisting of only 0s, 1s, and 2s. Write a program to in-place sort the array without using inbuilt sort functions.

Will be using Dutch National flag Algorithm.

**Comment by MSubhajitIND** [comment]
> Given an array consisting of only 0s, 1s, and 2s. Write a program to in-place sort the array without using inbuilt sort functions.
> 
> Will be using Dutch National flag Algorithm.

Assigned You

**Comment by Wafmulla** [comment]
Hey can you assign this task to me ?
