### ISSUE TITLE
Add Odd-Even Sort / Brick Sort

### ISSUE THREAD

**Issue by shanvijha30** [random957654/Hactober-2023-1#201]
Odd-Even Sort / Brick Sort :
This algorithm is divided into two phases- Odd and Even Phase. The algorithm runs until the array elements are sorted and in each iteration two phases occurs- Odd and Even Phases.

Feature :
Add Odd-Even Sort / Brick Sort in Python.

Description of solution :
Will add Odd-Even Sort / Brick Sort with adequate comments and proper documentation for readers to get a clear understanding.
To be added in Java.

Alternatives Considered :
Could you please assign me this issue under Hacktoberfest 2023.

**Comment by MSubhajitIND** [comment]
Assigned You

> Odd-Even Sort / Brick Sort : This algorithm is divided into two phases- Odd and Even Phase. The algorithm runs until the array elements are sorted and in each iteration two phases occurs- Odd and Even Phases.
> 
> Feature : Add Odd-Even Sort / Brick Sort in Python.
> 
> Description of solution : Will add Odd-Even Sort / Brick Sort with adequate comments and proper documentation for readers to get a clear understanding. To be added in Java.
> 
> Alternatives Considered : Could you please assign me this issue under Hacktoberfest 2023.

Assigned You

**Comment by shanvijha30** [comment]
@MSubhajitIND Can you let me know that is your project excluded from Hacktoberfest 2023.

**Comment by MSubhajitIND** [comment]
> @MSubhajitIND Can you let me know that is your project excluded from Hacktoberfest 2023.

In issue there i mentioned it.....

Sadly Hacktoberfest 2023 is not for beginners anymore all repos are excluded... only legit projects pike cal.com /Freecodecamp, appwrite like repos are legit...you have to contribute on this....

Please read #86 their i mentioned everything

**Comment by Soumojitshome2023** [comment]
Binary Searching

#include <stdio.h>
int binarySearch(int arr[], int size, int element){
    int low, mid, high;
    low = 0;
    high = size - 1;
    // Keep searching until low <= high
    while (low <= high){
        mid = (low + high) / 2;
        if (arr[mid] == element){
            return mid;
        }
        if (arr[mid] < element) {
            low = mid + 1;
        }
        else{
            high = mid - 1;
        }
    }
    return -1;
}
int main(){
    // Sorted array for binary search
    int arr[] = {1, 3, 5, 56, 64, 73, 123, 225, 444};
    int size = sizeof(arr) / sizeof(int);
    int element = 444;
    int searchIndex = binarySearch(arr, size, element);
    printf("The element %d was found at index %d \n", element, searchIndex);
    return 0;
}

**Comment by prafull904434** [comment]
sir
can you assign to me

**Comment by Wafmulla** [comment]
Hello can you please assign this issue to me under Hacktoberfest label?
