### ISSUE TITLE
Restructure the whole code in the proper directories

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [random957654/Hactober-2023-1#323]
- There are a lots of code which will be useful for the users.
- But it is not in the structured form so that user can take advantage of it.
- I would like to restuctured the whole code so that it will be useful and interactive.
- Provide a cool experience to the users.

**Comment by Avdhesh-Varshney** [comment]
@random957654 please assign this task to me to contribute under hacktoberfest 2023

**Comment by Harsh76200** [comment]
**hey @random957654 Let me do this task,I will take care of it !**

## what I will do ?

> I will sort all your files in proper format in O(1) complexity

**Comment by Harsh76200** [comment]
Done @random957654 👍
