### ISSUE TITLE
repo excluded

### ISSUE THREAD

**Issue by Raunakkumarr** [random957654/Hactober-2023-1#329]
![image](https://github.com/random957654/Hactober-2023-1/assets/52267072/76609384-3ac7-4de9-9b8d-34791703ab75)

**Comment by TheKidPadra** [comment]
I just opened my first pull request and I saw this too.
Does this mean I can't contribute?

**Comment by Raunakkumarr** [comment]
@TheKidPadra no it means that contributing to this repo doesn't count to your hacktoberfest contribution anymore. You can still contribute to other repositories.

**Comment by MSubhajitIND** [comment]
@Raunakkumarr  @TheKidPadra Other Repos also excluded as per 2023 Hacktoberfest rule ... you can only contribute legit.
**You will find opensource Official Repos From This link provided by hacktoberfest authorities.**
https://hacktoberfest-projects.vercel.app/

**Comment by TheKidPadra** [comment]
Thank you so much this is going to be helpful 
I really appreciate this
