### ISSUE TITLE
Problem: Minimum Edit Distance (Levenshtein Distance)

### ISSUE THREAD

**Issue by Sidd7000** [random957654/Hactober-2023-1#414]
You are given two strings, str1 and str2. Your task is to find the minimum number of operations (insertion, deletion, or substitution) required to transform str1 into str2.

Write a C++ program to calculate the minimum edit distance between two strings.

**Comment by siddharth7000** [comment]
Please assign this issue to me

**Comment by Kruti-Amrutiya** [comment]
@MSubhajitIND can you please assign this issue to me also as my PR is already merged?

**Comment by ShrutikaK2911** [comment]
Assign me the issue

**Comment by Manan-Arora31** [comment]
@Sidd7000 Pls assign this to me
