### ISSUE TITLE
Implement Circular Queue In C++

### ISSUE THREAD

**Issue by mrsamirr** [random957654/Hactober-2023-1#507]
![Screenshot_2023-10-21-17-50-06-13_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://github.com/random957654/Hactober-2023-1/assets/115770126/cec2d0ef-bf80-434b-9515-4c84cc05e09a)
Why my PR is excluded from hacktoberfest?
This Repo is not counting on hacktoberfest @MSubhajitIND ?

**Comment by MSubhajitIND** [comment]
@mrsamirr this and all other Repos also excluded as per 2023 Hacktoberfest rule ... you can only contribute legit.
You will find opensource Official Repos From This link provided by hacktoberfest authorities. Pull in Repos like Freecodecamp, Appwrite will count.
https://hacktoberfest-projects.vercel.app/
