### ISSUE TITLE
Create C++ Program to Check Kaprekar Number for Specific Base

### ISSUE THREAD

**Issue by purnasth** [random957654/Hactober-2023-1#580]
# Issue Title: Create C++ Program to Check Kaprekar Number for Specific Base

## Issue Description:
I propose to contribute a C++ program that checks whether a given number is a Kaprekar number for a specific base. Kaprekar numbers are a fascinating mathematical concept, and providing a C++ program to identify them for a specified base will be a valuable addition to our collection of C and C++ programs.

## Program Details (if available):
If there are specific details or requirements for the C++ program, please provide them to ensure it aligns with the project's goals.

I am excited to work on this and contribute to our growing collection of C and C++ programs.

**Comment by ShubhAgarwal0704** [comment]
please assign me this task.

**Comment by GauraviVeling** [comment]
Hello. Please can you assign this issue to me . I would like contributing to the issue.
