### ISSUE TITLE
Adding new leetcode problem in c/c++

### ISSUE THREAD

**Issue by vandana3869** [random957654/Hactober-2023-1#608]
Adding Minimize the Heights II leetcode problem

**Comment by vandana3869** [comment]
@Subhojit666  can you please assign this?

**Comment by adarsh-k27r** [comment]
I will be glad to do this.

**Comment by MSubhajitIND** [comment]
> This repo is excluded from hacktober2023! But still, I would do it once I'm free. 🙂 @vandana3869 @MSubhajitIND 

Please read #86 .... I explained why excluded
