### ISSUE TITLE
Feat: Add Wave Print Matrix C++ Program

### ISSUE THREAD

**Issue by khushis28** [random957654/Hactober-2023-1#629]
This program prints a matrix (a two-dimensional array) in a "wave-like" pattern. In other words, it might print the elements of the matrix in a way that resembles the motion of a wave.

For example, if you have a 2D matrix like this:

1 2 3
4 5 6
7 8 9

A "wave print" of this matrix could look like:

1 4 7 8 5 2 3 6 9

**Comment by kalaSriSaiRaksha** [comment]
assign me this issue
