### ISSUE TITLE
feat: Adding a 3D Flip Portfolio Card Project 

### ISSUE THREAD

**Issue by khushis28** [random957654/Hactober-2023-1#641]
About :
This project is a simple implementation of a 3D flip portfolio card using HTML and CSS. It allows you to showcase your portfolio items including social handles in an interactive way.

DEMO: 
You can see a live demo of the project : https://3d-flip-portfolio-card.netlify.app/

Features: 
* 3D flip effect on hover
* Easily customizable
* Responsive design

**Comment by MSubhajitIND** [comment]
This is C/CPP repo
