### ISSUE TITLE
Adding Binary Search Problem

### ISSUE THREAD

**Issue by tanisha91** [random957654/Hactober-2023-1#71]

**Comment by abhaygzb15** [comment]
@tanisha91 Hey!! It would be grateful for me if you could assign this issue to me under hactoberfest.

**Comment by tanisha91** [comment]
Okay

**Comment by MSubhajitIND** [comment]
I assigned Abhay as per conversation in this issue

**Comment by Amisha328** [comment]
Hi @MSubhajitIND,

Please review and accept the PR #86.

Thank you !! :)

**Comment by MSubhajitIND** [comment]
@abhaygzb15 you too can add another program related to binary search... if you want to work on this let me know...other wise i will close this issue in 24 hours.

Thanks

**Comment by MSubhajitIND** [comment]
> Hi @MSubhajitIND,
> 
> Please review and accept the PR #86.
> 
> Thank you !! :)

Thank You

**Comment by abhaygzb15** [comment]
@MSubhajitIND I will submit the work within 24 hours.

**Comment by riddhi-283** [comment]
@MSubhajitIND please assign this to me , I can add solutions for more binary search problems or solutions to the exiting one as well

**Comment by MSubhajitIND** [comment]
@riddhi-283 @abhaygzb15 Both are assigned.

**Comment by Jugnu-Gupta** [comment]
@MSubhajitIND could you please assign this task to me, i would like to contribute.

**Comment by Jugnu-Gupta** [comment]
check my pull request for binary search problem

**Comment by Jugnu-Gupta** [comment]
@MSubhajitIND i have send it again

**Comment by Ashima2003** [comment]
@random957654 Please look into my PR.

**Comment by MSubhajitIND** [comment]
> @random957654 Please look into my PR.
> 

I aproved

**Comment by anshul-132002** [comment]
Kindly assign this task to me...

**Comment by anshul-132002** [comment]
bro why my pull request is EXCLUDED ?
