### ISSUE TITLE
Adding kadane Algorithm

### ISSUE THREAD

**Issue by tanisha91** [random957654/Hactober-2023-1#72]

**Comment by tanisha91** [comment]
Please Assign it to  me

**Comment by MSubhajitIND** [comment]
You can work now I assigned you

**Comment by Ashima2003** [comment]
I wish to contribute. Kindly assign me this issue.

**Comment by Jugnu-Gupta** [comment]
@random957654 could you please assign this task to me.
Kadane algorithm is used to find the sum of the contiguous subarray within a arr[] with the largest sum.

**Comment by Jugnu-Gupta** [comment]
@MSubhajitIND check my PR

**Comment by tanisha91** [comment]
> You can work now I assigned you

Thank you
