### ISSUE TITLE
Sieve of eratosthenes

### ISSUE THREAD

**Issue by bhaveshgarg2000** [random957654/Hactober-2023-1#81]
Hi, The Moderator assign this issue. I'm keenly interested in this @random957654

**Comment by MSubhajitIND** [comment]
I assigned you...Please explain what you gonna add

**Comment by bhaveshgarg2000** [comment]
I'll add Sieve of Eratosthenes Algorithm in c++

**Comment by Ashima2003** [comment]
I wish to contribute. Kindly assign me this issue.

**Comment by Jugnu-Gupta** [comment]
@random957654 could you please assign this task to me.
Sieve of Erathosthenes is used to find all the prime numbers less than or equal to a given integer n by the Eratosthene’s method: 
When the algorithm terminates, all the numbers in the list that are not marked are prime.

**Comment by bhaveshgarg2000** [comment]
@random957654 I have created PR related to this Issue
Add Please give me Hacktoberfest Tag
Thanks

**Comment by MSubhajitIND** [comment]
> @random957654 I have created PR related to this Issue Add Please give me Hacktoberfest Tag Thanks

This will automatically add during merge ... still i added here... Please read #86 for Hacktoberfest.
