### ISSUE TITLE
Programs on Dynamic Programming

### ISSUE THREAD

**Issue by Amisha328** [random957654/Hactober-2023-1#87]
Issue to add programs on the advanced algorithm - Dynamic Programming.

**Comment by Amisha328** [comment]
Hi @MSubhajitIND, 
Please assign the issue to me, I wanted to add some programs on Dynamic Programming in C++.

**Comment by MSubhajitIND** [comment]
Assigned You

**Comment by Amisha328** [comment]
> Assigned You

Thank you !! Working on it.

**Comment by riddhi-283** [comment]
Hello @MSubhajitIND, kindly assign this issue to me . 
I want to contribute some Dynamic Programming codes in C++.

**Comment by MSubhajitIND** [comment]
@riddhi-283 @Amisha328 Assigned Both... You Both can contribute.

**Comment by Amisha328** [comment]
Hi @MSubhajitIND ,

Please review and accept the PR #88.

Thank you !! :)

**Comment by riddhi-283** [comment]
Hello @MSubhajitIND , please review the code and accept my PR
